

# simple Makefile 


all:
	gcc server.c -o server
	gcc client.c -o client

all2:
	gcc server_ok.c -o server_ok
	gcc client_ok.c -o client_ok


clean:
	rm -f server
	rm -f client


clean2:
	rm -f server_ok
	rm -rf client_ok


PHONY := all clean all2 client_ok




